import DontIndex from "@/components/Various/Seo/DontIndex";
import { Card } from "@/components/ui/card";
import React from "react";

function Privacy() {
  return (
    <Card>
      <DontIndex />
      <h1>Privacy policy</h1>

      <div>
        <p>Effective date: 01/10/2023</p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>Introduction</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>Welcome to&nbsp;WonderRail.</p>
        <p>&nbsp;</p>
        <p>
          WonderRail&nbsp;(“us”, “we”, or “our”)
          operates&nbsp;https://wonderrail.com&nbsp;(hereinafter referred to as
          “Service”).
        </p>
        <p>&nbsp;</p>
        <p>
          Our Privacy Policy governs your visit to https://wonderrail.com, and
          explains how we collect, safeguard and disclose information that
          results from your use of our Service.&nbsp;
        </p>
        <p>&nbsp;</p>
        <p>
          We use your data to provide and improve Service. By using Service, you
          agree to the collection and use of information in accordance with this
          policy. Unless otherwise defined in this Privacy Policy, the terms
          used in this Privacy Policy have the same meanings as in our Terms and
          Conditions.
        </p>
        <p>&nbsp;</p>
        <p>
          Our Terms and Conditions (“Terms”) govern all use of our Service and
          together with the Privacy Policy constitutes your agreement with us
          (“agreement”).
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>Definitions</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          WonderRail&nbsp;means the&nbsp;https://wonderrail.com
          website&nbsp;operated by&nbsp;WonderRail.
        </p>
        <p>&nbsp;</p>
        <p>
          PERSONAL DATA&nbsp;means data about a living individual who can be
          identified from those data (or from those and other information either
          in our possession or likely to come into our possession).
        </p>
        <p>&nbsp;</p>
        <p>
          USAGE DATA&nbsp;is data collected automatically either generated by
          the use of Service or from Service infrastructure itself (for example,
          the duration of a page visit).
        </p>
        <p>&nbsp;</p>
        <p>
          COOKIES&nbsp;are small files stored on your device (computer or mobile
          device).
        </p>
        <p>&nbsp;</p>
        <p>
          DATA CONTROLLER&nbsp;means a natural or legal person who (either alone
          or jointly or in common with other persons) determines the purposes
          for which and the manner in which any personal data are, or are to be,
          processed. For the purpose of this Privacy Policy, we are a Data
          Controller of your data.
        </p>
        <p>&nbsp;</p>
        <p>
          DATA PROCESSORS (OR WonderRail PROVIDERS)&nbsp;means any natural or
          legal person who processes the data on behalf of the Data Controller.
          We may use the services of various Service Providers in order to
          process your data more effectively.
        </p>
        <p>&nbsp;</p>
        <p>
          DATA SUBJECT&nbsp;is any living individual who is the subject of
          Personal Data.
        </p>
        <p>&nbsp;</p>
        <p>
          THE USER&nbsp;is the individual using our Service. The User
          corresponds to the Data Subject, who is the subject of Personal Data.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>Information Collection and Use</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={4}>
          <li>
            <p>Types of Data Collected</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>Personal Data</p>
        <p>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“Personal Data”). Personally identifiable information
          may include, but is not limited to:
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>Email address</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>First name and last name</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>Phone number</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={4}>
          <li>
            <p>Cookies and Usage Data</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us&nbsp;by following the unsubscribe link.
        </p>
        <p>&nbsp;</p>
        <p>Usage Data</p>
        <p>
          We may also collect information that your browser sends whenever you
          visit our Service or when you access Service by or through a mobile
          device (“Usage Data”).
        </p>
        <p>&nbsp;</p>
        <p>
          This Usage Data may include information such as your computer&apos;s
          Internet Protocol address (e.g. IP address), browser type, browser
          version, the pages of our Service that you visit, the time and date of
          your visit, the time spent on those pages, unique device identifiers
          and other diagnostic data.
        </p>
        <p>&nbsp;</p>
        <p>
          When you access Service with a mobile device, this Usage Data may
          include information such as the type of mobile device you use, your
          mobile device unique ID, the IP address of your mobile device, your
          mobile operating system, the type of mobile Internet browser you use,
          unique device identifiers and other diagnostic data.
        </p>
        <p>&nbsp;</p>
        <p>Tracking Cookies Data</p>
        <p>
          We use cookies and similar tracking technologies to track the activity
          on our Service and we hold certain information.
        </p>
        <p>&nbsp;</p>
        <p>
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Other tracking technologies are
          also used such as beacons, tags and scripts to collect and track
          information and to improve and analyze our Service.
        </p>
        <p>&nbsp;</p>
        <p>
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>
        <p>&nbsp;</p>
        <p>Examples of Cookies we use:</p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>
              Session Cookies:&nbsp;We use Session Cookies to operate our
              Service.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>
              Preference Cookies:&nbsp;We use Preference Cookies to remember
              your preferences and various settings.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>
              Security Cookies:&nbsp;We use Security Cookies for security
              purposes.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={4}>
          <li>
            <p>
              Advertising Cookies:&nbsp;Advertising Cookies are used to serve
              you with advertisements that may be relevant to you and your
              interests.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>Other Data</p>
        <p>
          While using our Service, we may also collect the following
          information: sex, age, date of birth, place of birth, passport
          details, citizenship, registration at place of residence and actual
          address, telephone number (work, mobile), details of documents on
          education, qualification, professional training, employment
          agreements, non-disclosure agreements, information on bonuses and
          compensation, information on marital status, family members, social
          security (or other taxpayer identification) number, office location
          and other data.&nbsp;
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={5}>
          <li>
            <p>Use of Data</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>WonderRail&nbsp;uses the collected data for various purposes:</p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>to provide and maintain our Service;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>to notify you about changes to our Service;&nbsp;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>
              to allow you to participate in interactive features of our Service
              when you choose to do so;&nbsp;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={4}>
          <li>
            <p>to provide customer support;&nbsp;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={5}>
          <li>
            <p>
              to gather analysis or valuable information so that we can improve
              our Service;&nbsp;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={6}>
          <li>
            <p>to monitor the usage of our Service;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={7}>
          <li>
            <p>to detect, prevent and address technical issues;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={8}>
          <li>
            <p>to fulfill any other purpose for which you provide it;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={9}>
          <li>
            <p>
              to carry out our obligations and enforce our rights arising from
              any contracts entered into between you and us, including for
              billing and collection;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={10}>
          <li>
            <p>
              to provide you with notices about your account and/or
              subscription, including expiration and renewal notices,
              email-instructions, etc.;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={11}>
          <li>
            <p>
              to provide you with news, special offers and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired about
              unless you have opted not to receive such information;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={12}>
          <li>
            <p>
              in any other way we may describe when you provide the information;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={13}>
          <li>
            <p>for any other purpose with your consent.&nbsp;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={6}>
          <li>
            <p>Retention of Data</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies.
        </p>
        <p>&nbsp;</p>
        <p>
          We will also retain Usage Data for internal analysis purposes. Usage
          Data is generally retained for a shorter period, except when this data
          is used to strengthen the security or to improve the functionality of
          our Service, or we are legally obligated to retain this data for
          longer time periods.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={7}>
          <li>
            <p>Transfer of Data</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          Your information, including Personal Data, may be transferred to – and
          maintained on – computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction.
        </p>
        <p>&nbsp;</p>
        <p>
          If you are located outside United States and choose to provide
          information to us, please note that we transfer the data, including
          Personal Data, to United States and process it there.
        </p>
        <p>&nbsp;</p>
        <p>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <p>&nbsp;</p>
        <p>
          WonderRail&nbsp;will take all the steps reasonably necessary to ensure
          that your data is treated securely and in accordance with this Privacy
          Policy and no transfer of your Personal Data will take place to an
          organisation or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={8}>
          <li>
            <p>Disclosure of Data</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We may disclose personal information that we collect, or you provide:
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>Disclosure for Law Enforcement.</p>
          </li>
        </ol>
        <p>
          Under certain circumstances, we may be required to disclose your
          Personal Data if required to do so by law or in response to valid
          requests by public authorities.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>Business Transaction.</p>
          </li>
        </ol>
        <p>
          If we or our subsidiaries are involved in a merger, acquisition or
          asset sale, your Personal Data may be transferred.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>Other cases. We may disclose your information also:</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>to our subsidiaries and affiliates;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>
              to contractors, service providers, and other third parties we use
              to support our business;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>to fulfill the purpose for which you provide it;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={4}>
          <li>
            <p>with your consent in any other cases;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={9}>
          <li>
            <p>Security of Data</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={10}>
          <li>
            <p>
              Your Data Protection Rights Under General Data Protection
              Regulation (GDPR)
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          If you are a resident of the European Union (EU) and European Economic
          Area (EEA), you have certain data protection rights, covered by GDPR.
          – See more at&nbsp;
          <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj">
            https://eur-lex.europa.eu/eli/reg/2016/679/oj
          </a>
          &nbsp;
        </p>
        <p>&nbsp;</p>
        <p>
          We aim to take reasonable steps to allow you to correct, amend,
          delete, or limit the use of your Personal Data.
        </p>
        <p>&nbsp;</p>
        <p>
          If you wish to be informed what Personal Data we hold about you and if
          you want it to be removed from our systems, please email us at
          mail@wonderrail.com.&nbsp;
        </p>
        <p>&nbsp;</p>
        <p>
          In certain circumstances, you have the following data protection
          rights:
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>
              the right to access, update or to delete the information we have
              on you;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>
              the right of rectification. You have the right to have your
              information rectified if that information is inaccurate or
              incomplete;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>
              the right to object. You have the right to object to our
              processing of your Personal Data;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={4}>
          <li>
            <p>
              the right of restriction. You have the right to request that we
              restrict the processing of your personal information;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={5}>
          <li>
            <p>
              the right to data portability. You have the right to be provided
              with a copy of your Personal Data in a structured,
              machine-readable and commonly used format;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={6}>
          <li>
            <p>
              the right to withdraw consent.&nbsp;You also have the right to
              withdraw your consent at any time where we rely on your consent to
              process your personal information;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          Please note that we may ask you to verify your identity before
          responding to such requests. Please note, we may not able to provide
          Service without some necessary data.
        </p>
        <p>&nbsp;</p>
        <p>
          You have the right to complain to a Data Protection Authority about
          our collection and use of your Personal Data. For more information,
          please contact your local data protection authority in the European
          Economic Area (EEA).
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={11}>
          <li>
            <p>
              Your Data Protection Rights under the California Privacy
              Protection Act (CalOPPA)
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          CalOPPA is the first state law in the nation to require commercial
          websites and online services to post a privacy policy. The law’s reach
          stretches well beyond California to require a person or company in the
          United States (and conceivable the world) that operates websites
          collecting personally identifiable information from California
          consumers to post a conspicuous privacy policy on its website stating
          exactly the information being collected and those individuals with
          whom it is being shared, and to comply with this policy. – See more
          at:&nbsp;
          <a href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/">
            https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
          </a>
          &nbsp;
        </p>
        <p>&nbsp;</p>
        <p>According to CalOPPA we agree to the following:</p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>users can visit our site anonymously;</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>
              our Privacy Policy link includes the word “Privacy”, and can
              easily be found on the page specified above on the home page of
              our website;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>
              users will be notified of any privacy policy changes on our
              Privacy Policy Page;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={4}>
          <li>
            <p>
              users are able to change their personal information by emailing us
              at mail@wonderrail.com.&nbsp;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>Our Policy on “Do Not Track” Signals:</p>
        <p>&nbsp;</p>
        <p>
          We honor Do Not Track signals and do not track, plant cookies, or use
          advertising when a Do Not Track browser mechanism is in place. Do Not
          Track is a preference you can set in your web browser to inform
          websites that you do not want to be tracked.&nbsp;
        </p>
        <p>&nbsp;</p>
        <p>
          You can enable or disable Do Not Track by visiting the Preferences or
          Settings page of your web browser.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={12}>
          <li>
            <p>
              Your Data Protection Rights under the California Consumer Privacy
              Act (CCPA)
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          If you are a California resident, you are entitled to learn what data
          we collect about you, ask to delete your data and not to sell (share)
          it. To exercise your data protection rights, you can make certain
          requests and ask us:
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>
              What personal information we have about you. If you make this
              request, we will return to you:
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside">
          <li>
            <p>
              The categories of personal information we have collected about
              you.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>
              The categories of sources from which we collect your personal
              information.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>
              The business or commercial purpose for collecting or selling your
              personal information.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={4}>
          <li>
            <p>
              The categories of third parties with whom we share personal
              information.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={5}>
          <li>
            <p>
              The specific pieces of personal information we have collected
              about you.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={6}>
          <li>
            <p>
              A list of categories of personal information that we have sold,
              along with the category of any other company we sold it to. If we
              have not sold your personal information, we will inform you of
              that fact.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={7}>
          <li>
            <p>
              A list of categories of personal information that we have
              disclosed for a business purpose, along with the category of any
              other company we shared it with.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          Please note, you are entitled to ask us to provide you with this
          information up to two times in a rolling twelve-month period. When you
          make this request, the information provided may be limited to the
          personal information we collected about you in the previous
          12&nbsp;months.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={2}>
          <li>
            <p>
              To delete your personal information. If you make this request, we
              will delete the personal information we hold about you as of the
              date of your request from our records and direct any service
              providers to do the same. In some cases, deletion may be
              accomplished through de-identification of the information. If you
              choose to delete your personal information, you may not be able to
              use certain functions that require your personal information to
              operate.&nbsp;
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={3}>
          <li>
            <p>
              To stop selling your personal information. If you submit a request
              to stop selling your personal information, we will stop selling
              it. If you are a California resident, to opt-out of the sale of
              your personal information, click “Do Not Sell My Personal
              Information” at the bottom of our home page to submit your
              request.
            </p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          Please note, if you ask us to delete or stop selling your data, it may
          impact your experience with us, and you may not be able to participate
          in certain programs or membership services which require the usage of
          your personal information to function. But in no circumstances, we
          will discriminate against you for exercising your rights.
        </p>
        <p>&nbsp;</p>
        <p>
          To exercise your California data protection rights described above,
          please send your request(s) by one of the following means:
        </p>
        <p>&nbsp;</p>
        <p>By email: mail@wonderrail.com</p>
        <p>&nbsp;</p>
        <p>
          Your data protection rights, described above, are covered by the CCPA,
          short for the California Consumer Privacy Act. To find out more, visit
          the official&nbsp;
          <a href="http://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201720180AB375">
            California Legislative Information website
          </a>
          . The CCPA took effect on 01/01/2020.&nbsp;
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={13}>
          <li>
            <p>Service Providers</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We may employ third party companies and individuals to facilitate our
          Service (“Service Providers”), provide Service on our behalf, perform
          Service-related services or assist us in analysing how our Service is
          used.
        </p>
        <p>&nbsp;</p>
        <p>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={14}>
          <li>
            <p>Analytics</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We may use third-party Service Providers to monitor and analyze the
          use of our Service.
        </p>
        <p>&nbsp;</p>
        <p>Google Analytics</p>
        <p>
          Google Analytics is a web analytics service offered by Google that
          tracks and reports website traffic. Google uses the data collected to
          track and monitor the use of our Service. This data is shared with
          other Google services. Google may use the collected data to
          contextualise and personalise the ads of its own advertising network.
        </p>
        <p>&nbsp;</p>
        <p>
          For more information on the privacy practices of Google, please visit
          the Google Privacy Terms web page:&nbsp;
          <a href="https://policies.google.com/privacy?hl=en">
            https://policies.google.com/privacy?hl=en
          </a>
        </p>
        <p>&nbsp;</p>
        <p>
          We also encourage you to review the Google&apos;s policy for
          safeguarding your data:&nbsp;
          <a href="https://support.google.com/analytics/answer/6004245">
            https://support.google.com/analytics/answer/6004245
          </a>
          .
        </p>
        <p>&nbsp;</p>
        <p>Firebase</p>
        <p>Firebase is analytics service provided by Google Inc.</p>
        <p>&nbsp;</p>
        <p>
          You may opt-out of certain Firebase features through your mobile
          device settings, such as your device advertising settings or by
          following the instructions provided by Google in their Privacy
          Policy:&nbsp;
          <a href="https://policies.google.com/privacy?hl=en">
            https://policies.google.com/privacy?hl=en
          </a>
        </p>
        <p>&nbsp;</p>
        <p>
          For more information on what type of information Firebase collects,
          please visit the Google Privacy Terms web page:&nbsp;
          <a href="https://policies.google.com/privacy?hl=en">
            https://policies.google.com/privacy?hl=en
          </a>
        </p>
        <p>&nbsp;</p>
        <p>Cloudflare analytics</p>
        <p>
          Cloudflare analytics is a web analytics service operated by Cloudflare
          Inc. Read the Privacy Policy here:&nbsp;
          <a href="https://www.cloudflare.com/privacypolicy/">
            https://www.cloudflare.com/privacypolicy/
          </a>
          &nbsp;
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={15}>
          <li>
            <p>CI/CD tools</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We may use third-party Service Providers to automate the development
          process of our Service.&nbsp;
        </p>
        <p>&nbsp;</p>
        <p>GitHub</p>
        <p>&nbsp;</p>
        <p>GitHub is provided by GitHub, Inc.</p>
        <p>&nbsp;</p>
        <p>
          GitHub is a development platform to host and review code, manage
          projects, and build software.
        </p>
        <p>&nbsp;</p>
        <p>
          For more information on what data GitHub collects for what purpose and
          how the protection of the data is ensured, please visit GitHub Privacy
          Policy page:&nbsp;
          <a href="https://help.github.com/en/articles/github-privacy-statement">
            https://help.github.com/en/articles/github-privacy-statement
          </a>
          .
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={16}>
          <li>
            <p>Advertising</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We may use third-party Service Providers to show advertisements to you
          to help support and maintain our Service.
        </p>
        <p>&nbsp;</p>
        <p>Google AdSense DoubleClick Cookie</p>
        <p>
          Google, as a third party vendor, uses cookies to serve ads on our
          Service. Google&apos;s use of the DoubleClick cookie enables it and
          its partners to serve ads to our users based on their visit to our
          Service or other websites on the Internet.
        </p>
        <p>&nbsp;</p>
        <p>
          You may opt out of the use of the DoubleClick Cookie for
          interest-based advertising by visiting the Google Ads Settings web
          page:&nbsp;
          <a href="http://www.google.com/ads/preferences/">
            http://www.google.com/ads/preferences/
          </a>
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={17}>
          <li>
            <p>Behavioral Remarketing</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          WonderRail&nbsp;uses remarketing services to advertise on third party
          websites to you after you visited our Service. We and our third-party
          vendors use cookies to inform, optimise and serve ads based on your
          past visits to our Service.
        </p>
        <p>&nbsp;</p>
        <p>Google Ads (AdWords)</p>
        <p>
          Google Ads (AdWords) remarketing service is provided by Google Inc.
        </p>
        <p>&nbsp;</p>
        <p>
          You can opt-out of Google Analytics for Display Advertising and
          customize the Google Display Network ads by visiting the Google Ads
          Settings page:&nbsp;
          <a href="http://www.google.com/settings/ads">
            http://www.google.com/settings/ads
          </a>
        </p>
        <p>&nbsp;</p>
        <p>
          Google also recommends installing the Google Analytics Opt-out Browser
          Add-on –&nbsp;
          <a href="https://tools.google.com/dlpage/gaoptout">
            https://tools.google.com/dlpage/gaoptout
          </a>{" "}
          – for your web browser. Google Analytics Opt-out Browser Add-on
          provides visitors with the ability to prevent their data from being
          collected and used by Google Analytics.
        </p>
        <p>&nbsp;</p>
        <p>
          For more information on the privacy practices of Google, please visit
          the Google Privacy Terms web page:&nbsp;
          <a href="https://policies.google.com/privacy?hl=en">
            https://policies.google.com/privacy?hl=en
          </a>
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={18}>
          <li>
            <p>Payments</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We may provide paid products and/or services within Service. In that
          case, we use third-party services for payment processing (e.g. payment
          processors).
        </p>
        <p>&nbsp;</p>
        <p>
          We will not store or collect your payment card details. That
          information is provided directly to our third-party payment processors
          whose use of your personal information is governed by their Privacy
          Policy. These payment processors adhere to the standards set by
          PCI-DSS as managed by the PCI Security Standards Council, which is a
          joint effort of brands like Visa, Mastercard, American Express and
          Discover. PCI-DSS requirements help ensure the secure handling of
          payment information.
        </p>
        <p>&nbsp;</p>
        <p>The payment processors we work with are:</p>
        <p>&nbsp;</p>
        <p>PayPal or Braintree:</p>
        <p>
          Their Privacy Policy can be viewed at&nbsp;
          <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full">
            https://www.paypal.com/webapps/mpp/ua/privacy-full
          </a>
        </p>
        <p>&nbsp;</p>
        <p>Apple Store In-App Payments:</p>
        <p>
          Their Privacy Policy can be viewed at:&nbsp;
          <a href="https://www.apple.com/legal/privacy/en-ww/">
            https://www.apple.com/legal/privacy/en-ww/
          </a>{" "}
          /&nbsp;
          <a href="https://support.apple.com/en-us/HT203027">
            https://support.apple.com/en-us/HT203027
          </a>
          &nbsp;
        </p>
        <p>&nbsp;</p>
        <p>Google Play In-App Payments:</p>
        <p>
          Their Privacy Policy can be viewed at:&nbsp;
          <a href="https://policies.google.com/privacy?hl=en&gl=us">
            https://policies.google.com/privacy?hl=en&amp;gl=us
          </a>{" "}
          /&nbsp;
          <a href="https://payments.google.com/payments/apis-secure/u/0/get_legal_document?ldo=0&ldt=privacynotice&ldl=en">
            https://payments.google.com/payments/apis-secure/u/0/get_legal_document?ldo=0&amp;ldt=privacynotice&amp;ldl=en
          </a>
          &nbsp;
        </p>
        <p>&nbsp;</p>
        <p>Stripe:</p>
        <p>
          Their Privacy Policy can be viewed at:&nbsp;
          <a href="https://stripe.com/us/privacy">
            https://stripe.com/us/privacy
          </a>
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={19}>
          <li>
            <p>Links to Other Sites</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          Our Service may contain links to other sites that are not operated by
          us. If you click a third party link, you will be directed to that
          third party&apos;s site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </p>
        <p>&nbsp;</p>
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={20}>
          <li>
            <p>Children&apos;s Privacy</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          Our Services are not intended for use by children under the age of 18
          (“Child” or “Children”).&nbsp;
        </p>
        <p>&nbsp;</p>
        <p>
          We do not knowingly collect personally identifiable information from
          Children under 18. If you become aware that a Child has provided us
          with Personal Data, please contact us. If we become aware that we have
          collected Personal Data from Children without verification of parental
          consent, we take steps to remove that information from our servers.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={21}>
          <li>
            <p>Changes to This Privacy Policy</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>&nbsp;</p>
        <p>
          We will let you know via email and/or a prominent notice on our
          Service, prior to the change becoming effective and update “effective
          date” at the top of this Privacy Policy.
        </p>
        <p>&nbsp;</p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <p>&nbsp;</p>
        <ol className="list-decimal list-inside" start={22}>
          <li>
            <p>Contact Us</p>
          </li>
        </ol>
        <p>&nbsp;</p>
        <p>
          If you have any questions about this Privacy Policy, please contact
          us:
        </p>
        <p>&nbsp;</p>
        <p>By email: mail@wonderrail.com.</p>
        <p>&nbsp;</p>
      </div>
    </Card>
  );
}

export default Privacy;
